"use client";

// Session-wide card store. Cards are captured at first-tap (in the tracker)
// and read on the /gallery page, so they need to survive route navigation.
// sessionStorage persists across Next.js route transitions within a tab and
// clears on tab close, which matches the "this session" semantic.
//
// Entries hold a data-URL thumbnail (~40–150 KB each) and a short
// conversation history. sessionStorage caps at a few MB on most browsers,
// so the store self-trims to MAX_CARDS and history to MAX_HISTORY per card.

import { useEffect, useState } from "react";

export type AppLang = "en" | "zh";

// The lens active when this card was captured. Snapshotted at first-tap
// so the gallery can filter/tint by lens even after the user switches
// modes later in the session.
export type CardMode = "play" | "language" | "history";

export type ChatTurn = {
  role: "user" | "assistant";
  content: string;
};

export type GeneratedImageStatus = "idle" | "pending" | "done" | "failed";

export type SessionCard = {
  id: string;
  trackId: string;
  createdAt: number;
  // YOLO-emitted class ("cup", "chair") is kept internally for matching
  // but NEVER shown to the user. `objectName` is what the VLM called
  // this specific thing (e.g. "ceramic mug") and is used everywhere
  // user-facing.
  className: string;
  objectName?: string;
  description: string;
  voiceId: string;
  line: string;
  imageDataUrl: string;

  // Conversation memory — appended each time a turn completes on either the
  // tracker or the gallery. Capped per-card at MAX_HISTORY.
  history?: ChatTurn[];

  // Comic-style illustration generated by Runware from the card's
  // className + description + conversation topic. Filled lazily after the
  // user clicks the "collect" button in the tracker popup.
  generatedImageUrl?: string;
  generatedImagePrompt?: string;
  generatedImageStatus?: GeneratedImageStatus;
  generatedImageError?: string | null;

  // Language pair at the time of capture. spokenLang = what the user
  // speaks, learnLang = the target they want to practice. teachMode is
  // derived from conversation topic (set when the LLM sees the user asking
  // about translation / word meaning / grammar).
  spokenLang?: AppLang;
  learnLang?: AppLang;
  teachMode?: boolean;

  // Lens at capture time. Absent for cards from before the multi-lens
  // release — treat those as "play" when filtering.
  mode?: CardMode;
};

const STORAGE_KEY = "omni.sessionCards.v2";
const MAX_CARDS = 40;
const MAX_HISTORY = 24;

let cards: readonly SessionCard[] = [];
let hydrated = false;
const listeners = new Set<(cards: readonly SessionCard[]) => void>();

function hydrate() {
  if (hydrated || typeof window === "undefined") return;
  hydrated = true;
  try {
    const raw = window.sessionStorage.getItem(STORAGE_KEY);
    if (!raw) return;
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) {
      cards = parsed.filter(
        (c): c is SessionCard =>
          !!c &&
          typeof c.id === "string" &&
          typeof c.trackId === "string" &&
          typeof c.className === "string" &&
          typeof c.description === "string" &&
          typeof c.voiceId === "string" &&
          typeof c.line === "string" &&
          typeof c.imageDataUrl === "string"
      );
    }
  } catch {
    // Corrupt storage — start fresh.
  }
}

function persist() {
  if (typeof window === "undefined") return;
  try {
    window.sessionStorage.setItem(STORAGE_KEY, JSON.stringify(cards));
  } catch {
    // Quota exceeded (crops + histories are big). Trim aggressively and
    // retry once.
    cards = cards.slice(-Math.floor(MAX_CARDS / 2));
    try {
      window.sessionStorage.setItem(STORAGE_KEY, JSON.stringify(cards));
    } catch {
      // Give up — in-memory state is still correct, persistence just fails.
    }
  }
}

function emit() {
  for (const cb of listeners) cb(cards);
}

function updateCard(
  predicate: (card: SessionCard) => boolean,
  patch: (card: SessionCard) => SessionCard
): boolean {
  hydrate();
  let changed = false;
  const next = cards.map((c) => {
    if (!predicate(c)) return c;
    const updated = patch(c);
    if (updated === c) return c;
    changed = true;
    return updated;
  });
  if (!changed) return false;
  cards = next;
  persist();
  emit();
  return true;
}

export function getSessionCards(): readonly SessionCard[] {
  hydrate();
  return cards;
}

export function addSessionCard(card: SessionCard): void {
  hydrate();
  if (cards.some((c) => c.trackId === card.trackId)) return;
  cards = [...cards, card].slice(-MAX_CARDS);
  persist();
  emit();
}

export function removeSessionCard(id: string): void {
  hydrate();
  const next = cards.filter((c) => c.id !== id);
  if (next.length === cards.length) return;
  cards = next;
  persist();
  emit();
}

export function clearSessionCards(): void {
  hydrate();
  if (cards.length === 0) return;
  cards = [];
  persist();
  emit();
}

// --- Conversation history -------------------------------------------------

// Append one or more turns to the card's history. Dedupes consecutive
// identical assistant messages (the tracker's opening-line push and the
// first /api/speak turn can otherwise double up).
export function appendCardHistory(
  lookup: { cardId?: string; trackId?: string },
  turns: readonly ChatTurn[]
): boolean {
  if (turns.length === 0) return false;
  return updateCard(
    (c) =>
      (lookup.cardId != null && c.id === lookup.cardId) ||
      (lookup.trackId != null && c.trackId === lookup.trackId),
    (c) => {
      const prior = c.history ?? [];
      const combined = [...prior];
      for (const t of turns) {
        if (!t || !t.content || !t.content.trim()) continue;
        const last = combined[combined.length - 1];
        if (last && last.role === t.role && last.content === t.content) {
          continue;
        }
        combined.push({ role: t.role, content: t.content });
      }
      if (combined.length === prior.length) return c;
      return { ...c, history: combined.slice(-MAX_HISTORY) };
    }
  );
}

// --- Generated image -----------------------------------------------------

export function setCardImageStatus(
  cardId: string,
  status: GeneratedImageStatus,
  extra?: { prompt?: string; error?: string | null }
): boolean {
  return updateCard(
    (c) => c.id === cardId,
    (c) => ({
      ...c,
      generatedImageStatus: status,
      generatedImagePrompt: extra?.prompt ?? c.generatedImagePrompt,
      generatedImageError:
        extra?.error !== undefined ? extra.error : c.generatedImageError,
    })
  );
}

export function setCardGeneratedImage(
  cardId: string,
  imageUrl: string,
  prompt: string
): boolean {
  return updateCard(
    (c) => c.id === cardId,
    (c) => ({
      ...c,
      generatedImageUrl: imageUrl,
      generatedImagePrompt: prompt,
      generatedImageStatus: "done",
      generatedImageError: null,
    })
  );
}

// --- Language / teach mode -----------------------------------------------

export function setCardLanguages(
  trackId: string,
  spokenLang: AppLang,
  learnLang: AppLang
): boolean {
  return updateCard(
    (c) => c.trackId === trackId,
    (c) => {
      if (c.spokenLang === spokenLang && c.learnLang === learnLang) return c;
      return { ...c, spokenLang, learnLang };
    }
  );
}

// User-facing label for a card. Prefers the VLM's short name, falls
// back to the Chinese "未命名" / English "item" when missing — never
// the raw YOLO class, per product rule.
export function cardDisplayName(
  card: Pick<SessionCard, "objectName" | "spokenLang" | "learnLang">
): string {
  const n = card.objectName?.trim();
  if (n) return n;
  const lang = card.learnLang ?? card.spokenLang ?? "zh";
  return lang === "zh" ? "未命名" : "unnamed";
}

export function setCardObjectName(trackId: string, name: string): boolean {
  const trimmed = name.trim();
  if (!trimmed) return false;
  return updateCard(
    (c) => c.trackId === trackId,
    (c) => (c.objectName === trimmed ? c : { ...c, objectName: trimmed })
  );
}

export function setCardTeachMode(trackId: string, teachMode: boolean): boolean {
  return updateCard(
    (c) => c.trackId === trackId,
    (c) => (c.teachMode === teachMode ? c : { ...c, teachMode })
  );
}

export function subscribeSessionCards(
  cb: (cards: readonly SessionCard[]) => void
): () => void {
  listeners.add(cb);
  return () => {
    listeners.delete(cb);
  };
}

// React hook — hydrates on mount, resubscribes on storage change from other
// tabs so the gallery stays in sync if the tracker is open in another tab.
export function useSessionCards(): readonly SessionCard[] {
  const [state, setState] = useState<readonly SessionCard[]>(() => cards);
  useEffect(() => {
    hydrate();
    setState(cards);
    const unsub = subscribeSessionCards(setState);
    const onStorage = (e: StorageEvent) => {
      if (e.key !== STORAGE_KEY) return;
      // Another tab wrote — rehydrate from storage.
      hydrated = false;
      cards = [];
      hydrate();
      setState(cards);
      emit();
    };
    window.addEventListener("storage", onStorage);
    return () => {
      unsub();
      window.removeEventListener("storage", onStorage);
    };
  }, []);
  return state;
}
